JERDDEL/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'localization/index'

  resources :contacts
  resources :promotions
  resources :videos
  resources :relevants
  get 'config/index'

  resources :products
  resources :providers
  resources :welcome
  resources :galleries
  resources :informations

  get 'galleries/index'
  get 'welcome/index'

  root 'welcome#index'

end

JERDDEL/app/controllers/config_controller.rb
class ConfigController < ApplicationController
  def index
    @information = Information.all
  end
end

JERDDEL/app/helpers/config_helper.rb
module ConfigHelper
end

JERDDEL/app/views/config/index.html.erb
<article class="text-center page-header">
   <h1>Configuracion de Contenido</h1>
</article>
<article class="text-justify text-primary">
  <h3>Este apartado sirve para modificar los contenidos de las siguientes secciones.</h3>
</article>
<fieldset class="form-group">
  <article class="page-header">
    <h1><span class='label label-default'>Inicio</span></h1>
    <% @id = 1 %>
    <%= link_to "Galeria de Imagenes", {:controller  => "galleries", :action => "index", :id => @id}, class: "btn btn-primary"%>
    <%= link_to "Productos Relevantes", relevants_path , class: "btn btn-primary"%>
    <%= link_to "Videos de Experiencias", {:controller  => "videos", :action => "index", :id => @id} , class: "btn btn-primary"%>
  </article>
</fieldset>

<fieldset class="form-group">
  <article class="page-header">
    <% @id = 2 %>
    <h1><span class='label label-default'>Promociones</span></h1>
    <%= link_to "Galeria de Imagenes", {:controller  => "galleries", :action => "index", :id => @id}, :method => :get , class: "btn btn-primary"%>
    <%= link_to "Videos de Experiencias", {:controller  => "videos", :action => "index", :id => @id}, :method => :get , class: "btn btn-primary"%>
  </article>
</fieldset>

<fieldset class="form-group">
  <article class="page-header">
    <h1><span class='label label-default'>Contáctanos</span></h1>
    <%= link_to "Localización", contacts_path , class: "btn btn-primary"%>
  </article>
</fieldset>

<fieldset class="form-group">
  <article class="page-header">
    <h1><span class='label label-default'>¿Quienes somos?</span></h1>
    <% @information.each do |information|
      information.history %>
      <%= link_to "¿Quienes somos?", edit_information_path(information) , class: "btn btn-primary"%>
    <%end%>
  </article>
</fieldset>