JERDDEL/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'localization/index'

  resources :contacts
  resources :promotions
  resources :videos
  resources :relevants
  get 'config/index'

  resources :products
  resources :providers
  resources :welcome
  resources :galleries
  resources :informations

  get 'galleries/index'
  get 'welcome/index'

  root 'welcome#index'

end

JERDDEL/app/models/provider.rb
class Provider < ActiveRecord::Base
  belongs_to :state
  validates :name, presence: {message: "Obligatorio"}
  validates :phone, presence: {message: "Obligatorio"}
  validates :street, presence: {message: "Obligatorio"}
  validates :colony, presence: {message: "Obligatorio"}
  validates :number, presence: {message: "Obligatorio"}
  validates :state_id, presence: {message: "Obligatorio"}

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      default_scoped
    end
  end
end

JERDDEL/app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.search(params[:search]).order(:name).paginate(page: params[:page],per_page:(6))
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @accion = "Guardar"
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
    @accion = "Actualizar"
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Proveedor fue guardado exitosamente.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Proveedor fue actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Proveedor fue eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:name, :phone, :street, :colony, :number, :state_id)
    end
end

JERDDEL/app/helpers/providers_helper.rb
module ProvidersHelper
end

JERDDEL/app/views/providers/_form.html.erb
<%= form_for(@provider,role:"form") do |f|%>
  <% if @provider.errors.any? %>
    <div id="error_explanation">
      <h2>No se pudo guaradar el proveedor ocurrieron <%= pluralize(@provider.errors.count, "errore") %>: </h2>

      <ul>
      <% @provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
  <div class="file">
    <%= f.label :nombre %><br>
    <%= f.text_field :name, class: "form-control" %>
    </div>
    </div>

    <div class="form-group">
  <div class="file">
    <%= f.label :telefono %><br>
    <%= f.text_field :phone, class: "form-control" %>
  </div>
    </div>

    <div class="form-group">
  <div class="field">
    <%= f.label :calle %><br>
    <%= f.text_field :street, class: "form-control" %>
  </div>
      </div>

      <div class="form-group">
  <div class="field">
    <%= f.label :numbero %><br>
    <%= f.number_field :number, class: "form-control" %>
  </div>
      </div>

    <div class="form-group">
      <div class="field">
        <%= f.label :colonia %><br>
        <%= f.text_field :colony, class: "form-control" %>
      </div>
    </div>

      <div class="form-group">
  <div class="field ">
    <%= f.label :estado %><br>
    <%= f.collection_select(:state_id, State.order(:state),:id, :state, {prompt: "--Selecciona una opción--" }, {class: "form-control"}) %>
  </div>
        </div>

  <div class="actions">
    <%= f.submit @accion, class: "btn btn-success" %>
  </div>

<% end %>

JERDDEL/app/views/providers/edit.html.erb
<article class="container page-header" style="width: 60%;">
  <article class="panel panel-primary">
    <article class="panel-heading">
      <h1>Editar Proveedor</h1>
    </article>
    <article class="panel-body">
      <%= render 'form' %>

      <%= link_to 'Mostrar', @provider, class: "btn btn-info" %>
      <%= link_to 'Regresar', providers_path, class: "btn btn-danger" %>
    </article>
  </article>
</article>

JERDDEL/app/views/providers/index.html.erb
<article class="text-center page-header">
<h1>Lista de Proveedores</h1>
</article>
<%= link_to 'Nuevo Proveedor', new_provider_path, class: "btn btn-success" %>

<article class="form-inline container text-center">
  <article>
    <i>Busqueda por nombre del proveedor:</i>
  </article>
  <%= form_tag providers_path, :method => 'get' do %>
      <article class="form-group">
        <%= text_field_tag :search, params[:search],class: "form-control" %>
      </article>
      <article class="form-group">
        <%= submit_tag "Buscar", :name => nil, class: "btn btn-default form-control" %>
  <% end %>
  </article>
</article>
<hr>

<hr>
<table class="table table-responsive">
  <thead class="text-info">
    <tr>
      <th>Nombre</th>
      <th>Telefono</th>
      <th>Calle</th>
      <th>Colonia</th>
      <th>Numero</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @providers.each do |provider| %>
      <tr>
        <td><%= provider.name %></td>
        <td><%= provider.phone %></td>
        <td><%= provider.street %></td>
        <td><%= provider.colony %></td>
        <td><%= provider.number %></td>
        <td><%= provider.state.state %></td>
        <td><%= link_to 'Mostrar', provider, class: "btn btn-info" %></td>
        <td><%= link_to 'Editar', edit_provider_path(provider), class: "btn btn-warning" %></td>
        <td><%= link_to 'Eliminar', provider, class: "btn btn-danger ", method: :delete, data: { confirm: '¿Estas Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

JERDDEL/app/views/providers/new.html.erb
<article class="container page-header" style="width: 60%;">
  <article class="panel panel-primary">
    <article class="panel-heading">
      <h1>Nuevo Proveedor</h1>
    </article>
    <article class="panel-body">
      <%= render 'form'%>
      <%= link_to 'Regresar', providers_path, class: "btn btn-danger" %>
    </article>
  </article>
</article>

JERDDEL/app/views/providers/show.html.erb
<article class="panel panel-primary page-header">
  <article class="panel-heading text-center">
    <h3 class="panel-title"><%= @provider.name %></h3>
  </article>
  <article class="panel-body">
    <p class="text-center">

<p>
  <strong>Telefono:</strong>
  <%= @provider.phone %>
</p>

<p>
  <strong>Calle:</strong>
  <%= @provider.street %>
</p>

<p>
  <strong>Numbero:</strong>
  <%= @provider.number %>
</p>

<p>
  <strong>Colonia:</strong>
  <%= @provider.colony %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @provider.state.state %>
</p>

<%= link_to 'Editar', edit_provider_path(@provider), class: "btn btn-info" %>
<%= link_to 'Regresar', providers_path, class: "btn btn-danger" %>
</article>
</article>