JERDDEL/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'localization/index'

  resources :contacts
  resources :promotions
  resources :videos
  resources :relevants
  get 'config/index'

  resources :products
  resources :providers
  resources :welcome
  resources :galleries
  resources :informations

  get 'galleries/index'
  get 'welcome/index'

  root 'welcome#index'

end

JERDDEL/app/models/contact.rb
class Contact < ActiveRecord::Base
  CONTACT_IMAGENES = File.join Rails.root, 'public', 'contact_store'
  after_save :guardar_imagen_contact

  def imagen_contact=(file_data_contact)
    unless file_data_contact.blank?
      @file_data_contact = file_data_contact
      self.extension = file_data_contact.original_filename.split(".").last.downcase
    end
  end

  def imagen_contact_filename
    File.join CONTACT_IMAGENES, "#{id}.#{extension}"
  end

  def imagen_path_contact
    "/contact_store/#{id}.#{extension}"
  end

  def has_imagen_contact?
    File.exists? imagen_contact_filename
  end

  private

  def guardar_imagen_contact
    if @file_data_contact
      FileUtils.mkdir_p CONTACT_IMAGENES
      File.open(imagen_contact_filename, 'wb') do |f|
        f.write(@file_data_contact.read)
      end
      @file_data_contact = nil
    end
  end
end

JERDDEL/app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :product
  validates :tipo, presence: {message: "Obligatorio"}
  validates :product_id, presence: {message: "Obligatorio"}
end

JERDDEL/app/models/information.rb
class Information < ActiveRecord::Base
  belongs_to :information
  validates :history, presence: {message: "Obligatorio"}
  validates :mission, presence: {message: "Obligatorio"}
  validates :vision, presence: {message: "Obligatorio"}
  validates :objetive, presence: {message: "Obligatorio"}
  validates :values, presence: {message: "Obligatorio"}
end

JERDDEL/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :provider
  validates :name, presence: {message: "Obligatorio"}
  validates :sale_price, presence: {message: "Obligatorio"}
  validates :purchase_price, presence: {message: "Obligatorio"}
  validates :use, presence: {message: "Obligatorio"}
  validates :cantidad, presence: {message: "Obligatorio"}
  validates :provider_id, presence: {message: "Obligatorio"}

  IMAGENES = File.join Rails.root, 'public', 'image_store'
  after_save :guardar_imagen

  def imagen=(file_data)
    unless file_data.blank?
      @file_data = file_data
      self.extension = file_data.original_filename.split(".").last.downcase
    end
  end

  def imagen_filename
    File.join IMAGENES, "#{id}.#{extension}"
  end

  def imagen_path
    "/image_store/#{id}.#{extension}"
  end

  def has_imagen?
    File.exists? imagen_filename
  end

  private

  def guardar_imagen
      if @file_data
        FileUtils.mkdir_p IMAGENES
        File.open(imagen_filename, 'wb') do |f|
          f.write(@file_data.read)
        end
        @file_data = nil
      end
  end

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      default_scoped
    end
  end
end

JERDDEL/app/models/provider.rb
class Provider < ActiveRecord::Base
  belongs_to :state
  validates :name, presence: {message: "Obligatorio"}
  validates :phone, presence: {message: "Obligatorio"}
  validates :street, presence: {message: "Obligatorio"}
  validates :colony, presence: {message: "Obligatorio"}
  validates :number, presence: {message: "Obligatorio"}
  validates :state_id, presence: {message: "Obligatorio"}

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      default_scoped
    end
  end
end

JERDDEL/app/models/relevant.rb
class Relevant < ActiveRecord::Base
  belongs_to :product
  validates :tipo, presence: {message: "Obligatorio"}
  validates :product_id, presence: {message: "Obligatorio"}
end

JERDDEL/app/models/state.rb
class State < ActiveRecord::Base
end

JERDDEL/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

JERDDEL/app/models/video.rb
class Video < ActiveRecord::Base
  validates :tipo, presence: {message: "Obligatorio"}
  validates :url, presence: {message: "Obligatorio"}
end

JERDDEL/app/controllers/config_controller.rb
class ConfigController < ApplicationController
  def index
    @information = Information.all
  end
end

JERDDEL/app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController

  def index
    @gallery = Gallery.all.where(tipo: "Promocion")
    @video = Video.all.where(tipo: "Promocion")
  end

  def show
    @gallery = Gallery.find(params[:id])
  end
end

JERDDEL/app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    @parametro = params[:id]
    @valor = @parametro
    if Integer(@valor) == 1
       @inicio = Video.all.where(tipo: "Inicio").paginate(page: params[:page],per_page:(3))
    elsif Integer(@valor) == 2
      @promocion = Video.all.where(tipo: "Promocion").paginate(page: params[:page],per_page:(3))
    end
  end

  def new
    @parametro = params[:id]
    @valor = @parametro
    if Integer(@valor) == 0
      @value = "Inicio"
    else
      @value = "Promocion"
    end
    @video = Video.new
  end

  def create
    @video = Video.new(videos_param)
    @valor = params[:video][:tipo]
    if @valor == "Inicio"
      @id = 1
    else
      @id = 2
    end
    if @video.save
      redirect_to videos_path(id: @id)
    else
      render :new
    end
  end

  def edit
    @video = Video.find(params[:id])
    @value = @video.tipo
  end

  def update
    @video = Video.find(params[:id])
    @valor = @video.tipo
    if @valor == "Inicio"
      @id = 1
    else
      @id = 2
    end
    if @video.update(videos_param)
      redirect_to videos_path(id: @id )
    else
      render :edit
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @valor = @video.tipo
    if @valor == "Inicio"
      @id = 1
    else
      @id = 2
    end
    @video.destroy
    redirect_to videos_path(id: @id )
  end

  private
  def videos_param
    params.required(:video).permit(:tipo,:url)
  end

end

JERDDEL/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @welcome = Product.all
    @gallery = Gallery.all.where(tipo: "Inicio")
    @information = Information.all
    @relevant = Relevant.all
    @video = Video.all.where(tipo: "Inicio")
  end

  def show
    @welcome = Product.find(params[:id])
  end

end

JERDDEL/app/helpers/application_helper.rb
module ApplicationHelper
end

JERDDEL/app/helpers/config_helper.rb
module ConfigHelper
end

JERDDEL/app/helpers/contacts_helper.rb
module ContactsHelper
end

JERDDEL/app/helpers/galleries_helper.rb
module GalleriesHelper
end

JERDDEL/app/helpers/localization_helper.rb
module LocalizationHelper
end

JERDDEL/app/helpers/products_helper.rb
module ProductsHelper
end

JERDDEL/app/helpers/providers_helper.rb
module ProvidersHelper
end

JERDDEL/app/helpers/welcome_helper.rb
module WelcomeHelper
end

JERDDEL/app/views/promotions/index.html.erb
<h1 class="page-header">Algunas de Nuestras Promociones</h1>
<!--Empieza bootstrap-->
<article class="carousel-size container">
  <article id="carousel-1" class="carousel slide" data-ride="carousel">
    <!--Inidcadore-->
    <ol class="carousel-indicators">
      <% for i in 0..(@gallery.size-1) do %>
          <li data-target="#carousel-1" data-slide-to="<%=i %>" class="<%if i == 0 then %> active<% end%>"></li>
      <%end%>
    </ol>
    <!--Contenedor de los slide-->
    <article class="carousel-inner" role="listbox">
      <% @gallery.each do |g|%>
          <article class="item <%if g.id == @gallery.first.id %>active <%else end %>">
            <img src="<%= if g.product.has_imagen? then g.product.imagen_path else '/assets/missing.jpg' end %>" class="img-responsive image-carousel">
            <article class="carousel-caption">
              <h3><%=g.product.name %></h3>
              <p><%=g.promocion %></p>
            </article>
          </article>
      <% end%>
    </article>
  </article>
</article>

<h1 class="page-header">Promociones</h1>
<article class="row">
  <% @gallery.each do |g| %>
      <article class="col-sm-4 text-center">
        <article class="panel panel-primary">
          <article class="panel-heading">
            <h3 class="panel-title"><%=g.product.name%></h3>
          </article>
          <article class="panel-body">
            <p>
              <%if g.product.has_imagen? %>
                  <%=image_tag(g.product.imagen_path, size:"200x150" )%>
              <% else %>
                  <%= image_tag("/assets/missing.jpg", size: "200x150")  %>
              <%end%>
            </p>
            <p><strong>Promocion:</strong><%=g.promocion%></p>
            <%= link_to(raw("<span class='glyphicon glyphicon-plus' aria-hidden='true'></span>"+' Mas Informacion'),{controller: 'promotions',action: 'show', id: g.id},class: "btn btn-info")%>
          </article>
        </article>
      </article>
  <%end%>
</article>


<h1 class="page-header">Videos</h1>
<div class="container text-center">
  <% @video.each do |v|%>
      <iframe class="video" src="https://www.youtube.com/embed/<%=v.url[v.url.index("=")+1,v.url.length] %>" frameborder="0" allowfullscreen></iframe>
  <%end%>
</div>
<hr>

JERDDEL/app/views/promotions/show.html.erb
<article class="panel panel-primary page-header">
  <article class="panel-heading text-center">
    <h3 class="panel-title"><%= @gallery.product.name %></h3>
  </article>
  <article class="panel-body">
    <p class="text-center">
      <%if @gallery.product.has_imagen? %>
          <%=image_tag(@gallery.product.imagen_path, size:"300x250" )%>
      <% else %>
          <%= image_tag("/assets/missing.jpg", size: "300x250")  %>
      <%end%>
    </p>
    <h3 class="text-center">
      <strong class="">Promocion:</strong><br>
      <%= @gallery.promocion %>
    </h3>
    <%= link_to 'Regresar', promotions_path, class: "btn btn-danger" %>
  </article>
</article>